import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { usePlanContext } from '../context/PlanContext';
import { useHabitContext } from '../context/HabitContext';
import { format, subMonths } from 'date-fns';

function DNAEvolutionPage() {
  const planCtx = usePlanContext();
  const hasFeature = planCtx.hasFeature;
  const { habits } = useHabitContext();
  const [evolutionData, setEvolutionData] = useState([]);
  const [currentPersonality, setCurrentPersonality] = useState('');
  const [shareCard, setShareCard] = useState(null);

  if (!hasFeature('dnaEvolution')) {
    return (
      <div style={{ padding: '24px', textAlign: 'center' }}>
        <h2>🚫 Elite Feature</h2>
        <p>This feature is available for Elite users only.</p>
      </div>
    );
  }

  useEffect(() => {
    generateEvolution();
  }, [habits]);

  const generateEvolution = () => {
    const months = [];
    for (let i = 5; i >= 0; i--) {
      const date = subMonths(new Date(), i);
      const avgStreak = Math.round(5 + Math.random() * 20 + (5 - i) * 3);
      const completionRate = Math.min(95, 40 + Math.random() * 30 + (5 - i) * 10);
      const habitsCount = Math.min(15, 3 + Math.floor((5 - i) * 2.5));
      
      months.push({
        month: format(date, 'MMM'),
        year: format(date, 'yyyy'),
        avgStreak,
        completionRate: Math.round(completionRate),
        habitsCount,
        traits: generateTraits(avgStreak, completionRate),
      });
    }

    setEvolutionData(months);

    const avgOverall = months.reduce((sum, m) => sum + m.avgStreak, 0) / months.length;
    const rateOverall = months.reduce((sum, m) => sum + m.completionRate, 0) / months.length;

    if (avgOverall > 25 && rateOverall > 80) {
      setCurrentPersonality('Habit Architect');
    } else if (avgOverall > 15 && rateOverall > 70) {
      setCurrentPersonality('Consistency Champion');
    } else if (avgOverall > 10) {
      setCurrentPersonality('Streak Builder');
    } else if (avgOverall > 5) {
      setCurrentPersonality('Early Adopter');
    } else {
      setCurrentPersonality('Fresh Starter');
    }
  };

  const generateTraits = (streak, rate) => {
    const traits = [];
    if (streak > 20) traits.push('Discipline Master');
    else if (streak > 10) traits.push('Routine Builder');
    else traits.push('Habit Learner');

    if (rate > 85) traits.push('High Achiever');
    else if (rate > 60) traits.push('Steady Performer');
    else traits.push('Growth Mindset');

    return traits;
  };

  const generateShareCard = () => {
    const cardData = {
      personality: currentPersonality,
      avgStreak: evolutionData[evolutionData.length - 1]?.avgStreak || 0,
      totalMonths: evolutionData.length,
      currentMonth: format(new Date(), 'MMMM yyyy'),
    };
    setShareCard(cardData);
    
    const canvas = document.createElement('canvas');
    canvas.width = 800;
    canvas.height = 600;
    const ctx = canvas.getContext('2d');
    
    ctx.fillStyle = '#1a1a2e';
    ctx.fillRect(0, 0, 800, 600);
    
    ctx.fillStyle = '#f59e0b';
    ctx.font = 'bold 48px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('🧬 DNA Evolution', 400, 80);
    
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 36px Arial';
    ctx.fillText(currentPersonality, 400, 180);
    
    ctx.fillStyle = '#888';
    ctx.font = '24px Arial';
    ctx.fillText(`Average Streak: ${cardData.avgStreak} days`, 400, 280);
    ctx.fillText(`Tracking Since: ${cardData.totalMonths} months`, 400, 330);
    
    ctx.fillStyle = '#BA7517';
    ctx.font = '20px Arial';
    ctx.fillText('Generated by HabitFlow Elite', 400, 550);
    
    const url = canvas.toDataURL();
    const a = document.createElement('a');
    a.href = url;
    a.download = 'dna-evolution-card.png';
    a.click();
  };

  return (
    <div style={{ padding: '24px', maxWidth: '900px', margin: '0 auto' }}>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div style={{ textAlign: 'center', marginBottom: '48px' }}>
          <div style={{ fontSize: '48px', marginBottom: '16px' }}>🧬</div>
          <h1 style={{ fontSize: '32px', fontWeight: 800, marginBottom: '8px' }}>
            DNA Evolution Timeline
          </h1>
          <p style={{ color: 'var(--text-secondary)' }}>
            Track your monthly personality evolution
          </p>
        </div>

        <div style={{
          background: 'linear-gradient(135deg, #BA7517, #f59e0b)',
          padding: '32px',
          borderRadius: '24px',
          color: 'white',
          textAlign: 'center',
          marginBottom: '32px'
        }}>
          <div style={{ fontSize: '14px', opacity: 0.9, marginBottom: '8px' }}>
            Current Habit Personality
          </div>
          <div style={{ fontSize: '40px', fontWeight: 800 }}>
            {currentPersonality}
          </div>
          <div style={{ marginTop: '16px', fontSize: '14px', opacity: 0.9 }}>
            Your habits have evolved over {evolutionData.length} months
          </div>
        </div>

        <h2 style={{ marginBottom: '24px' }}>6-Month Evolution</h2>
        <div style={{
          display: 'flex',
          gap: '12px',
          overflowX: 'auto',
          paddingBottom: '16px',
          marginBottom: '32px'
        }}>
          {evolutionData.map((month, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
              style={{
                minWidth: '140px',
                background: 'var(--surface)',
                padding: '20px',
                borderRadius: '16px',
                border: '1px solid var(--border)',
                textAlign: 'center'
              }}
            >
              <div style={{
                padding: '8px 16px',
                background: '#BA7517',
                color: 'white',
                borderRadius: '20px',
                fontSize: '12px',
                fontWeight: 600,
                marginBottom: '12px',
                display: 'inline-block'
              }}>
                {month.month}
              </div>
              <div style={{ fontSize: '32px', fontWeight: 700, marginBottom: '8px' }}>
                {month.avgStreak}
              </div>
              <div style={{ fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '12px' }}>
                avg streak
              </div>
              <div style={{
                width: '100%',
                height: '60px',
                display: 'flex',
                alignItems: 'flex-end',
                justifyContent: 'center',
                gap: '2px'
              }}>
                {[...Array(5)].map((_, i) => (
                  <div
                    key={i}
                    style={{
                      width: '16px',
                      height: `${20 + i * 10}px`,
                      background: i < Math.floor(month.completionRate / 20) ? '#BA7517' : 'var(--border)',
                      borderRadius: '4px'
                    }}
                  />
                ))}
              </div>
              <div style={{ fontSize: '12px', color: 'var(--text-secondary)', marginTop: '8px' }}>
                {month.completionRate}% rate
              </div>
            </motion.div>
          ))}
        </div>

        <h2 style={{ marginBottom: '24px' }}>Personality Traits</h2>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
          gap: '16px',
          marginBottom: '32px'
        }}>
          {evolutionData[evolutionData.length - 1]?.traits.map((trait, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              style={{
                background: 'var(--surface)',
                padding: '20px',
                borderRadius: '12px',
                border: '1px solid var(--border)',
                textAlign: 'center'
              }}
            >
              <div style={{ fontSize: '24px', marginBottom: '8px' }}>
                {idx === 0 ? '🎯' : idx === 1 ? '⭐' : '🚀'}
              </div>
              <div style={{ fontWeight: 600 }}>{trait}</div>
            </motion.div>
          ))}
        </div>

        <div style={{ textAlign: 'center' }}>
          <button
            onClick={generateShareCard}
            style={{
              padding: '16px 32px',
              background: 'linear-gradient(135deg, #BA7517, #f59e0b)',
              border: 'none',
              borderRadius: '12px',
              color: 'white',
              fontWeight: 700,
              cursor: 'pointer',
              fontSize: '16px'
            }}
          >
            📤 Generate & Share Card
          </button>
        </div>

        {shareCard && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            style={{
              marginTop: '24px',
              padding: '20px',
              background: 'var(--surface)',
              borderRadius: '16px',
              textAlign: 'center'
            }}
          >
            <p>Your DNA Evolution card has been downloaded!</p>
          </motion.div>
        )}
      </motion.div>
    </div>
  );
}

export default DNAEvolutionPage;