import { useState } from 'react';
import { motion } from 'framer-motion';
import { usePlanContext } from '../context/PlanContext';
import { useHabitContext } from '../context/HabitContext';
import { format, subMonths } from 'date-fns';

function MonthlyBehaviorReportPage() {
  const planCtx = usePlanContext();
  const hasFeature = planCtx.hasFeature;
  const { habits } = useHabitContext();
  const [isGenerating, setIsGenerating] = useState(false);
  const [report, setReport] = useState(null);

  if (!hasFeature('monthlyBehaviorReport')) {
    return (
      <div style={{ padding: '24px', textAlign: 'center' }}>
        <h2>🚫 Elite Feature</h2>
        <p>This feature is available for Elite users only.</p>
      </div>
    );
  }

  const generateReport = () => {
    setIsGenerating(true);
    
    setTimeout(() => {
      const analysis = analyzeBehavior();
      setReport(analysis);
      setIsGenerating(false);
    }, 2000);
  };

  const analyzeBehavior = () => {
    const totalHabits = habits.length;
    const completedHabits = habits.filter(h => h.currentStreak > 0).length;
    const avgStreak = habits.reduce((sum, h) => sum + (h.currentStreak || 0), 0) / (totalHabits || 1);
    const bestHabit = habits.reduce((best, h) => (h.currentStreak > (best?.currentStreak || 0) ? h : best), null);
    const mostDifficult = habits.reduce((hard, h) => (h.difficulty === 'extreme' ? hard + 1 : hard), 0);
    
    let personality = 'Discipline Seeker';
    if (avgStreak > 30) personality = 'Habit Master';
    else if (avgStreak > 14) personality = 'Consistency Champion';
    else if (avgStreak > 7) personality = 'Week Warrior';
    else if (avgStreak < 3) personality = 'Fresh Starter';

    const strengths = [];
    const weaknesses = [];

    if (avgStreak > 14) strengths.push('Exceptional consistency over 2+ weeks');
    if (completedHabits / totalHabits > 0.7) strengths.push('High completion rate (70%+)');
    if (bestHabit?.currentStreak > 30) strengths.push('Longest streak champion');

    if (avgStreak < 7) weaknesses.push('Building foundation - needs consistency');
    if (mostDifficult > 2) weaknesses.push('May be taking on too much extreme difficulty');
    if (totalHabits > 20 && avgStreak < 14) weaknesses.push('Too many habits - focus on fewer');

    return {
      month: format(new Date(), 'MMMM yyyy'),
      totalHabits,
      completedHabits,
      completionRate: Math.round((completedHabits / totalHabits) * 100),
      avgStreak: Math.round(avgStreak),
      bestHabit: bestHabit?.name || 'N/A',
      bestStreak: bestHabit?.currentStreak || 0,
      personality,
      strengths,
      weaknesses,
      recommendations: generateRecommendations(avgStreak, totalHabits, completedHabits),
      createdAt: format(new Date(), 'MMM d, yyyy h:mm a'),
    };
  };

  const generateRecommendations = (avgStreak, total, completed) => {
    const recs = [];
    if (avgStreak < 7) {
      recs.push('Start with 3 habits maximum for 2 weeks before adding more');
      recs.push('Focus on habit stacking - link new habits to existing ones');
    }
    if (completed / total < 0.6) {
      recs.push('Reduce habit difficulty - start easier and build up');
    }
    if (avgStreak > 14) {
      recs.push('Time to add more challenging habits or increase intensity');
    }
    recs.push('Consider habit templates for faster habit creation');
    return recs;
  };

  const downloadPDF = () => {
    const content = `
HABIT FLOW - MONTHLY BEHAVIOR REPORT
=====================================
Generated: ${report?.createdAt}

PERSONALITY: ${report?.personality}

OVERVIEW
--------
Total Habits: ${report?.totalHabits}
Active Habits: ${report?.completedHabits}
Completion Rate: ${report?.completionRate}%
Average Streak: ${report?.avgStreak} days
Best Habit: ${report?.bestHabit} (${report?.bestStreak} days)

STRENGTHS
---------
${report?.strengths.map(s => `• ${s}`).join('\n')}

AREAS TO IMPROVE
----------------
${report?.weaknesses.map(w => `• ${w}`).join('\n')}

RECOMMENDATIONS
---------------
${report?.recommendations.map(r => `• ${r}`).join('\n')}

---
Generated by HabitFlow Elite
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `behavior-report-${format(new Date(), 'yyyy-MM')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ padding: '24px', maxWidth: '900px', margin: '0 auto' }}>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div style={{ textAlign: 'center', marginBottom: '48px' }}>
          <div style={{ fontSize: '48px', marginBottom: '16px' }}>🧬</div>
          <h1 style={{ fontSize: '32px', fontWeight: 800, marginBottom: '8px' }}>
            Monthly Behavior Report
          </h1>
          <p style={{ color: 'var(--text-secondary)' }}>
            Deep psychological analysis of your habit patterns
          </p>
        </div>

        {!report && !isGenerating && (
          <div style={{ textAlign: 'center' }}>
            <div style={{
              background: 'var(--surface)',
              padding: '48px',
              borderRadius: '24px',
              marginBottom: '24px'
            }}>
              <div style={{ fontSize: '64px', marginBottom: '24px' }}>📊</div>
              <h2 style={{ marginBottom: '16px' }}>Generate Your Report</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: '24px' }}>
                Get a detailed PDF analysis of your habit personality,
                strengths, weaknesses, and science-based recommendations.
              </p>
              <button
                onClick={generateReport}
                style={{
                  padding: '16px 32px',
                  background: 'linear-gradient(135deg, #BA7517, #f59e0b)',
                  border: 'none',
                  borderRadius: '12px',
                  color: 'white',
                  fontWeight: 700,
                  fontSize: '18px',
                  cursor: 'pointer',
                }}
              >
                Generate Report 🚀
              </button>
            </div>
          </div>
        )}

        {isGenerating && (
          <div style={{ textAlign: 'center', padding: '48px' }}>
            <div style={{ fontSize: '48px', marginBottom: '24px' }}>⚙️</div>
            <h2>Generating your personalized report...</h2>
            <div style={{
              marginTop: '24px',
              height: '4px',
              background: 'var(--border)',
              borderRadius: '2px',
              overflow: 'hidden'
            }}>
              <motion.div
                animate={{ width: ['0%', '100%'] }}
                transition={{ duration: 2 }}
                style={{
                  height: '100%',
                  background: 'linear-gradient(135deg, #BA7517, #f59e0b)'
                }}
              />
            </div>
          </div>
        )}

        {report && (
          <div>
            <div style={{
              background: 'linear-gradient(135deg, #BA7517, #f59e0b)',
              padding: '32px',
              borderRadius: '24px',
              color: 'white',
              textAlign: 'center',
              marginBottom: '24px'
            }}>
              <div style={{ fontSize: '14px', opacity: 0.9, marginBottom: '8px' }}>
                Your Habit Personality
              </div>
              <div style={{ fontSize: '48px', fontWeight: 800 }}>
                {report.personality}
              </div>
              <div style={{ marginTop: '16px', opacity: 0.9, fontSize: '14px' }}>
                {report.month} Analysis
              </div>
            </div>

            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: '16px',
              marginBottom: '24px'
            }}>
              {[
                { label: 'Total Habits', value: report.totalHabits, icon: '📝' },
                { label: 'Completion Rate', value: `${report.completionRate}%`, icon: '✅' },
                { label: 'Avg Streak', value: `${report.avgStreak} days`, icon: '🔥' },
                { label: 'Best Habit', value: `${report.bestStreak} days`, icon: '⭐' },
              ].map((stat, idx) => (
                <div
                  key={idx}
                  style={{
                    background: 'var(--surface)',
                    padding: '20px',
                    borderRadius: '16px',
                    textAlign: 'center',
                    border: '1px solid var(--border)'
                  }}
                >
                  <div style={{ fontSize: '32px', marginBottom: '8px' }}>{stat.icon}</div>
                  <div style={{ fontSize: '24px', fontWeight: 700 }}>{stat.value}</div>
                  <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>{stat.label}</div>
                </div>
              ))}
            </div>

            <div style={{
              background: 'var(--surface)',
              padding: '24px',
              borderRadius: '16px',
              marginBottom: '16px',
              border: '1px solid var(--border)'
            }}>
              <h3 style={{ marginBottom: '16px' }}>💪 Strengths</h3>
              {report.strengths.map((s, idx) => (
                <div key={idx} style={{
                  padding: '12px',
                  background: 'rgba(34, 197, 94, 0.1)',
                  borderRadius: '8px',
                  marginBottom: '8px'
                }}>
                  ✅ {s}
                </div>
              ))}
            </div>

            <div style={{
              background: 'var(--surface)',
              padding: '24px',
              borderRadius: '16px',
              marginBottom: '16px',
              border: '1px solid var(--border)'
            }}>
              <h3 style={{ marginBottom: '16px' }}>📈 Areas to Improve</h3>
              {report.weaknesses.map((w, idx) => (
                <div key={idx} style={{
                  padding: '12px',
                  background: 'rgba(239, 68, 68, 0.1)',
                  borderRadius: '8px',
                  marginBottom: '8px'
                }}>
                  ⚠️ {w}
                </div>
              ))}
            </div>

            <div style={{
              background: 'var(--surface)',
              padding: '24px',
              borderRadius: '16px',
              marginBottom: '24px',
              border: '1px solid var(--border)'
            }}>
              <h3 style={{ marginBottom: '16px' }}>🎯 Recommendations</h3>
              {report.recommendations.map((r, idx) => (
                <div key={idx} style={{
                  padding: '12px',
                  borderBottom: '1px solid var(--border)'
                }}>
                  {idx + 1}. {r}
                </div>
              ))}
            </div>

            <div style={{ display: 'flex', gap: '12px', justifyContent: 'center' }}>
              <button
                onClick={downloadPDF}
                style={{
                  padding: '16px 32px',
                  background: 'linear-gradient(135deg, #BA7517, #f59e0b)',
                  border: 'none',
                  borderRadius: '12px',
                  color: 'white',
                  fontWeight: 700,
                  cursor: 'pointer',
                }}
              >
                📥 Download Report
              </button>
              <button
                onClick={() => setReport(null)}
                style={{
                  padding: '16px 32px',
                  background: 'var(--surface)',
                  border: '1px solid var(--border)',
                  borderRadius: '12px',
                  cursor: 'pointer',
                }}
              >
                Generate New
              </button>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
}

export default MonthlyBehaviorReportPage;